
/**
* Powerup controller which handles the powerup action on the player's screen.
*
* @class PowerUpController
* @classdesc Powerupcontroller
* @constructor
*/
function PowerUpController(){

	var powerupCDTimer = null;
	var playerCDTimer = null;
	var powerupRemovalTimer = null;
	var icon = null;
	var powerup = null;


	/**
	* Creates a powerup if no powerup is present already.
	*
	* @method PowerUpController
	* @param {number} leftOffset - The left offset of the screen of the player as to that of the mainscreen
	* @param {number} topOffset - The top offset of the screen of the player as to that of the mainscreen
	* @return {Object} - An object containing the type and position of the powerup.
	*/
	this.createPowerup = function(leftOffset, topOffset){
		if(powerup == null) { //Only one powerup will be present on the player's screen
			var type = randomPowerType(); //choose a radom type
			powerup = game.instantiate(new Powerup(Settings.powerupSize, type));
			
			randomPosition = getRandomPosition();
			powerup.setPosition(randomPosition.x, randomPosition.y);
			createIcon(type);

			powerupRemovalTimer = setTimeout(removePowerup, Settings.removalTime*1000); //set timer so powerup is removed after x seconds.
			powerupCoolDown((Settings.removalTime * 1000) / 90); //90 because we increment the angle by 4 (360/90 = 4)

			return {t: type, position: {
					x: randomPosition.x + leftOffset,
					y: randomPosition.y + topOffset,
			}};
		}
	};

	/**
	* Returns a random position for the powerup to be placed.
	*
	* @method PowerUpController
	* @return {Object} - The random position generated by the method.
	*/
	function getRandomPosition(){
		var chooser = Math.round(Math.random()); //random 0 or 1

		var width = Settings.canvasWidth;
		var height = Settings.canvasHeight;
		var shieldRadius = Settings.shield.radius;
		var powerupSize = Settings.powerupSize;
		
		var dx = Math.round(Math.random() * ((width - powerupSize) - (width/2 + shieldRadius + 2*powerupSize)) + ((shieldRadius + 2*powerupSize) * (1-chooser)));
		var dy = Math.round(Math.random() * ((height - powerupSize) - (height/2 + shieldRadius + 2*powerupSize)) + ((shieldRadius + 2*powerupSize) * chooser));
		
		//randomly decide whether to make x-coordinate negative
		if(Math.round(Math.random())) dx *= -1;
		 //randomly decide whether to make y-coordinate negative
		if(Math.round(Math.random())) dy *= -1;

		return {x: Settings.canvasWidth/2 + dx, y: Settings.canvasHeight/2 + dy};
	};

	/**
	* Chooses a random poweruptype depending on the given weight in the settings file.
	*
	* @method PowerUpController
	* @return {number} - The powerup type as a number
	*/
	function randomPowerType(){
		var random = Math.random();
		var chanceOfSmallShield = Settings.smallShield.chance;
		var chanceOfBigShield = Settings.bigShield.chance;
		var chanceOfSmallPole = Settings.smallPole.chance;
		var chanceOfBigPole = Settings.bigPole.chance;
		var chanceOfRevert = Settings.revertShield.chance;
		
		var sum = chanceOfSmallShield + chanceOfBigShield + chanceOfSmallPole + chanceOfBigPole + chanceOfRevert;
		
		if(random < chanceOfSmallShield/sum) return e.smallShield;
		if(random < (chanceOfSmallShield + chanceOfBigShield)/sum) return e.bigShield;
		if(random < (chanceOfSmallShield + chanceOfBigShield + chanceOfSmallPole)/sum) return e.smallPole;
		if(random < (chanceOfSmallShield + chanceOfBigShield + chanceOfSmallPole + chanceOfBigPole)/sum) return e.bigPole;
		//else
		return e.revertShield;
	};

	/**
	* Creates an icon depending on the powerup type
	* Note: each powerup can have its own path to a sprite.
	*
	* @method PowerUpController
	*/
	function createIcon(_type){
		switch(_type){
			case e.smallShield:
			icon = game.instantiate(new Sprite(Settings.smallShield.path));

			case e.bigShield:
			icon = game.instantiate(new Sprite(Settings.bigShield.path));

			case e.smallPole:
			icon = game.instantiate(new Sprite(Settings.smallPole.path));

			case e.bigPole:
			icon = game.instantiate(new Sprite(Settings.bigPole.path));

			case e.revertShield: 
			icon = game.instantiate(new Sprite(Settings.revertShield.path));
		}

		var size = Settings.powerupSize-2;
		icon.setPosition(powerup.getPosition());
		icon.setSize({x: size*2, y: size*2});
		icon.setAnchor({x: -size, y: -size});
	};

	/**
	* Checks whether the powerup is tapped by the player
	*
	* @method PowerUpController#checkPowerup
	* @param {number} _x - The x coordinate of the tap
	* @param {number} _y - The y coordinate of the tap
	* @return {Object} - An object containing the global playerID and the powerup type.
	*/
	this.checkPowerup = function(_x, _y){
		if(powerup != null){ //only when a powerup is present!
			if(!scale) scale = 1;
			var powerupPos = powerup.getPosition();

			//Check whether distance between powerup center and click is less than radius
			var inX = Math.abs(powerupPos.x*scale - _x) <= powerup.getRadius();
			var inY = Math.abs(powerupPos.y*scale - _y) <= powerup.getRadius();

			if(inX && inY){
				clearTimeout(powerupRemovalTimer); //remove the timer
				player.setPowerup(powerup); 
				playerCoolDown((powerup.getTimer().getTime() * 1000) / 90);

				var type = powerup.getType();
				removePowerup();
				return {gid: player.getGlobalID(), t: type};
			}
		}
	};

	/**
	* Removes the powerup + icon from the user's screen
	* 
	* @method PowerUpController#removePowerup
	*/
	function removePowerup(){
		if(powerup != null){
			game.remove(powerup);
			powerup = null;
		}
		if(icon != null) { 
			game.remove(icon);
			icon = null;
		}
	}

	/**
	* Instantiates the cooldown belonging to a powerup. 
	* It also removes any previous timeout that is present (to avoid cooldowns going to quick)
	*
	* @method PowerUpController#powerupCoolDown
	* @param {number} _time - The time in milliseconds at which the setTimeout function is called
	*/
	function powerupCoolDown(_time) {
		clearTimeout(powerupCDTimer); //Clear any old poweruptimeout that might be present
        powerup.setCDAngle(0);
        powerupCDTimer = setTimeout(function() { coolDown(powerup, _time); }, _time);
	}
	
	/**
	* Instantiates the cooldown belonging to a player after a powerup has been activated. 
	* It also removes any previous timeout that is present (to avoid cooldowns going to quick)
	*
	* @method PowerUpController#playerCoolDown
	* @param {number} _time - The time in milliseconds at which the setTimeout function is called
	*/
	function playerCoolDown(_time){
		clearTimeout(playerCDTimer); //Clear any old playertimeout that might be present
    	player.getPole().setCDAngle(0);		
    	playerCDTimer = setTimeout(function() { coolDown(pole, _time); }, _time);
    }

    /**
    * The cooldown function that is called by playerCoolDown and powerupCoolDown
    * It handles the actual coolDown and makes sure the angles are set and the function
    * is called again (until the cooldown is over)
    *
    * @method PowerUpController#coolDown
    * @param {Object} _object - The object which has the cooldown
    * @param {numer} _time - The time in milliseconds at which the setTimout function is called
    */
	function coolDown(_object, _time){
		if(_object != null){
			_object.incrementCDAngle(4);
			if(_object.getCDAngle() < 360) {
				if(_object instanceof Pole) {
					playerCDTimer = setTimeout(function() { coolDown(_object, _time); }, _time);
				} else {
					powerupCDTimer = setTimeout(function() { coolDown(_object, _time); }, _time);
				}
			}
		}
	}
}